---
include:
  - board: nice_nano//zmk
    shield: eyelash_sofle_left nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano//zmk
    shield: eyelash_sofle_right nice_view
  - board: nice_nano//zmk
    shield: settings_reset
